version: '3'
services:
  local-db:
    image: library/mariadb:10.0.11
    container_name: local-maria
    restart: always
    ports:
      - 13306:3306
    environment:
      MARIA_ROOT_PASSWORD: toot
      TZ: Asia/Seoul
    volumes:
      - ./